export const FETCH_LOGGED_USER = "FETCH_LOGGED_USER";
export const FETCH_LOGGED_USER_START = "FETCH_LOGGED_USER_START";
export const FETCH_LOGGED_USER_SUCCESS = "FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_FAIL = "FETCH_LOGGED_USER_FAIL";

export const APP_SET_LOADING = "APP_SET_LOADING"; 

// export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_START = "SIGNIN_USER_START";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";

// export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_START = "SIGNUP_USER_START";
// export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";