// export const FETCH_LOGGED_USER = "FETCH_LOGGED_USER";
export const FETCH_LOGGED_USER_START = "FETCH_LOGGED_USER_START";
export const FETCH_LOGGED_USER_SUCCESS = "FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_FAIL = "FETCH_LOGGED_USER_FAIL";

export const APP_SET_LOADING = "APP_SET_LOADING"; 

// export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_START = "SIGNIN_USER_START";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";

// export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_START = "SIGNUP_USER_START";
// export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";

export const SIGNOUT_USER_FINISH = "SIGNOUT_USER_FINISH";

export const ROOMS_FETCH_START = "ROOMS_FETCH_START";
export const ROOMS_FETCH_SUCCESS = "ROOMS_FETCH_SUCCESS";
export const ROOMS_FETCH_FAIL = "ROOMS_FETCH_FAIL"; 

export const ROOMS_CREATE_START = "ROOMS_CREATE_START";
export const ROOMS_CREATE_SUCCESS = "ROOMS_CREATE_SUCCESS";
export const ROOMS_CREATE_FAIL = "ROOMS_CREATE_FAIL";

export const ROOMS_CREATE_ROOM_SET_LOADING = "ROOMS_CREATE_ROOM_SET_LOADING";
export const ROOMS_SET_SHOW_CREATE_ROOM = "ROOMS_SET_SHOW_CREATE_ROOM";

export const ROOMS_DELETE_START = "ROOMS_DELETE_START";
export const ROOMS_DELETE_SUCCESS = "ROOMS_DELETE_SUCCESS";
export const ROOMS_DELETE_FAIL = "ROOMS_DELETE_FAIL";

export const ROOMS_REMOVE_USER_FROM_ROOM_START = "ROOMS_REMOVE_USER_FROM_ROOM_START";
export const ROOMS_REMOVE_USER_FROM_ROOM_SUCCESS = "ROOMS_REMOVE_USER_FROM_ROOM_SUCCESS";
export const ROOMS_REMOVE_USER_FROM_ROOM_FAIL = "ROOMS_REMOVE_USER_FROM_ROOM_FAIL";

export const ROOMS_LEAVE_ROOM_START = "ROOMS_LEAVE_ROOM_START";
export const ROOMS_LEAVE_ROOM_SUCCESS = "ROOMS_LEAVE_ROOM_SUCCESS";
export const ROOMS_LEAVE_ROOM_FAIL = "ROOMS_LEAVE_ROOM_FAIL";

export const ROOMS_SET_ACTIVE_ROOM = "ROOMS_SET_ACTIVE_ROOM";

export const MESSAGES_FETCH_START = "MESSAGES_FETCH_START";
export const MESSAGES_FETCH_SUCCESS = "MESSAGES_FETCH_SUCCESS";
export const MESSAGES_FETCH_FAIL = "MESSAGES_FETCH_FAIL";

export const MESSAGES_SET_ARE_DOWNLOADED_FOR_ROOM = "MESSAGES_SET_ARE_DOWNLOADED_FOR_ROOM";
export const MESSAGES_PREPARE_FOR_ROOM_SELECT = "MESSAGES_PREPARE_FOR_ROOM_SELECT";