export const FETCH_LOGGED_USER = "FETCH_LOGGED_USER";
export const FETCH_LOGGED_USER_START = "FETCH_LOGGED_USER_START";
export const FETCH_LOGGED_USER_SUCCESS = "FETCH_LOGGED_USER_SUCCESS";
export const FETCH_LOGGED_USER_FAIL = "FETCH_LOGGED_USER_FAIL";

export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_START = "SIGNIN_USER_START";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";